#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App2.Resource", IsApplication=true)]

namespace App2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int AddTagArray = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int addAsTemp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int addBill = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int addButt = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int addRec = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BG = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int BGLand = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dataPicker = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int day = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dayButt = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int decryotBut = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int encryptBut = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int exit = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int exitButt = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int exitLand = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int exitLandButt = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int exportBut = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int findBut = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_launcher = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int importBut = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int list = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int listButt = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int perButt = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int period = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int saveTemp = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int setPassBut = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int startBG = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int tagEditBut = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int tool = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int toolLand = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int toolsButt = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int toolsLandButt = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000e
			public const int ActDay = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int ActMonth = 2131099661;
			
			// aapt resource value: 0x7f060002
			public const int ActName = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int ActPrice = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int ActYear = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int Add = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int AddTagBut = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int AddTag_Header = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int AddTemp = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int AddTemplate = 2131099655;
			
			// aapt resource value: 0x7f06003d
			public const int Check = 2131099709;
			
			// aapt resource value: 0x7f060017
			public const int DayForDay = 2131099671;
			
			// aapt resource value: 0x7f060028
			public const int DayForPeriod_1 = 2131099688;
			
			// aapt resource value: 0x7f06002b
			public const int DayForPeriod_2 = 2131099691;
			
			// aapt resource value: 0x7f060018
			public const int FindForDayBut = 2131099672;
			
			// aapt resource value: 0x7f060025
			public const int FindForPerBut = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int FindForPeriod_EndDate = 2131099684;
			
			// aapt resource value: 0x7f060021
			public const int FindForPeriod_StartDate = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int FirstDataBut = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int LookForPeriod_SubHeader1 = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int LookForPeriod_SubHeader2 = 2131099682;
			
			// aapt resource value: 0x7f060031
			public const int LookTagBut = 2131099697;
			
			// aapt resource value: 0x7f060033
			public const int MainBut1 = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int MainBut2 = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int MainBut3 = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int MainBut4 = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int MainBut5 = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int MainBut6 = 2131099704;
			
			// aapt resource value: 0x7f060016
			public const int MonthForDay = 2131099670;
			
			// aapt resource value: 0x7f060027
			public const int MonthForPeriod_1 = 2131099687;
			
			// aapt resource value: 0x7f06002a
			public const int MonthForPeriod_2 = 2131099690;
			
			// aapt resource value: 0x7f060009
			public const int ParsePhoto = 2131099657;
			
			// aapt resource value: 0x7f060030
			public const int PossibleTag = 2131099696;
			
			// aapt resource value: 0x7f06003e
			public const int Prefs_Head = 2131099710;
			
			// aapt resource value: 0x7f060023
			public const int SecondDataBut = 2131099683;
			
			// aapt resource value: 0x7f060005
			public const int SetDateBut = 2131099653;
			
			// aapt resource value: 0x7f06004a
			public const int SetPass = 2131099722;
			
			// aapt resource value: 0x7f060048
			public const int SetPassField1 = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int SetPassField2 = 2131099721;
			
			// aapt resource value: 0x7f060006
			public const int SpinnerLayout = 2131099654;
			
			// aapt resource value: 0x7f06004c
			public const int StartButLay = 2131099724;
			
			// aapt resource value: 0x7f06001c
			public const int TableBrow = 2131099676;
			
			// aapt resource value: 0x7f060013
			public const int Table_All = 2131099667;
			
			// aapt resource value: 0x7f06001a
			public const int Table_Day = 2131099674;
			
			// aapt resource value: 0x7f06002d
			public const int Table_Per = 2131099693;
			
			// aapt resource value: 0x7f06004e
			public const int Table_Tag = 2131099726;
			
			// aapt resource value: 0x7f060044
			public const int TagEdition = 2131099716;
			
			// aapt resource value: 0x7f060010
			public const int TagName = 2131099664;
			
			// aapt resource value: 0x7f06004f
			public const int Temlpates_Header = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int Templates_All = 2131099728;
			
			// aapt resource value: 0x7f060000
			public const int TextViev1 = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int TextViev1_All = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int TextViev1_LookForDay = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int TextViev1_LookForDay_Req = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int TextViev1_LookForDay_Sum = 2131099675;
			
			// aapt resource value: 0x7f06002c
			public const int TextViev1_LookForPer_Req = 2131099692;
			
			// aapt resource value: 0x7f06002e
			public const int TextViev1_LookForPer_Sum = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int TextViev1_LookForTag = 2131099695;
			
			// aapt resource value: 0x7f060032
			public const int TextViev1_LookForTag_Req = 2131099698;
			
			// aapt resource value: 0x7f060001
			public const int TextViev2 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int TextViev3 = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int TextViev4 = 2131099659;
			
			// aapt resource value: 0x7f06003a
			public const int TextVievPass = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int TextVievPass2 = 2131099707;
			
			// aapt resource value: 0x7f060015
			public const int YearForDay = 2131099669;
			
			// aapt resource value: 0x7f060026
			public const int YearForPeriod_1 = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int YearForPeriod_2 = 2131099689;
			
			// aapt resource value: 0x7f06001d
			public const int backButt = 2131099677;
			
			// aapt resource value: 0x7f060047
			public const int browserElement = 2131099719;
			
			// aapt resource value: 0x7f06004d
			public const int button1 = 2131099725;
			
			// aapt resource value: 0x7f06001e
			public const int chooseButt = 2131099678;
			
			// aapt resource value: 0x7f060043
			public const int dec = 2131099715;
			
			// aapt resource value: 0x7f060039
			public const int descCol = 2131099705;
			
			// aapt resource value: 0x7f060042
			public const int enc = 2131099714;
			
			// aapt resource value: 0x7f06003f
			public const int expButt = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int impButt = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int passButt = 2131099713;
			
			// aapt resource value: 0x7f06003c
			public const int passField = 2131099708;
			
			// aapt resource value: 0x7f060045
			public const int priceCol = 2131099717;
			
			// aapt resource value: 0x7f06004b
			public const int relativeLayout1 = 2131099723;
			
			// aapt resource value: 0x7f060046
			public const int yearCol = 2131099718;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddRecLay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddTagLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AllCosts = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ComboBoxElement = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DayAct = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DayActRet = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FileExplorer = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FindForPeriodRequest = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int FindForPeriodRequested = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LookTagAct = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LookTagRet = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MainWindow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int OneTextTempate = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PasswordChecker = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Prefs = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int RowTemplate = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int RowTemplate2 = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int RowTemplate3 = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int separator = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SetPassLay = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Start = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int TagEdit = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int TemplateScreen = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int ThreeTextTemplate = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int TwoTextTemplate = 2130903064;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int BoldFont = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int LightFont = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int MediumFont = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
